{% set name = "scinumtools3" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/vrtulka23/scinumtools3/archive/refs/tags/v{{ version }}.tar.gz
    sha256: dd8e47093f844da6f3c5f2aea4afc786ab581040d311972e27755b9879edfce5
    folder: scinumtools3
  - url: https://github.com/vrtulka23/briefpp/archive/624aa478149a0fa0e7213bb7cfb6d19615d6e771.tar.gz
    sha256: aaac2a8a25f8a7bc11546038594eb9fef43bf560c0c0532a886c432d5e14de31
    folder: scinumtools3/external/briefpp

build:
  number: 0
  script: 
    - {{ PYTHON }} -m pip install scinumtools3 --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.24
    - ninja

  host:
    - hdf5
    - python
    - pip
    - scikit-build-core
    - pybind11
    - setuptools
    - wheel
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - scinumtools3

  commands:
    - python -c "import scinumtools3"

about:
  home: https://github.com/vrtulka23/scinumtools3
  summary: Python bindings for the SciNumTools3 C++ numerical library.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vrtulka23
