function(check_command expected_status expected_text)
  execute_process(COMMAND "${SNT_EXECUTABLE}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL expected_status OR NOT "${output}${error}" MATCHES "${expected_text}")
    message(FATAL_ERROR "Unexpected command result (${status}): ${ARGN}\n${output}${error}")
  endif()
endfunction()

check_command(0 "server" --help)
check_command(0 "view" --help)
check_command(1 "Unknown module" unknown-command)
if(SERVER_ENABLED)
  check_command(0 "Usage: snt server" server --help)
  check_command(2 "Port must be" server --port 0)
  check_command(2 "Missing value" server --port)
  check_command(2 "Unknown option" server --unknown)
else()
  check_command(1 "ENABLE_SNT_SERVER=ON" server --help)
endif()
if(VIEW_ENABLED)
  check_command(0 "future implementation" view --help)
  check_command(1 "not implemented" view)
else()
  check_command(1 "not included" view)
endif()
