include_guard(GLOBAL)

# Read one evaluated, unitless DIPL scalar into a normal caller-scope variable.
# OUT is retained as an alias for OUTPUT; REQUIRED is accepted for compatibility.
function(snt_dip_get)
    cmake_parse_arguments(PARSE_ARGV 0 ARG "REQUIRED" "FILE;PATH;OUTPUT;OUT;TYPE" "DEPENDS")
    if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "snt_dip_get(): unknown arguments or missing keyword values: ${ARG_UNPARSED_ARGUMENTS};${ARG_KEYWORDS_MISSING_VALUES}")
    endif()
    if(DEFINED ARG_OUT AND DEFINED ARG_OUTPUT)
        message(FATAL_ERROR "snt_dip_get(): use OUTPUT or OUT, not both.")
    endif()
    if(DEFINED ARG_OUT)
        set(ARG_OUTPUT "${ARG_OUT}")
    endif()
    foreach(key FILE PATH OUTPUT)
        if(NOT DEFINED ARG_${key} OR "${ARG_${key}}" STREQUAL "")
            message(FATAL_ERROR "snt_dip_get(): ${key} is required.")
        endif()
    endforeach()
    if(NOT ARG_OUTPUT MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "snt_dip_get(): OUTPUT must be a CMake variable name.")
    endif()
    set(type_args)
    if(DEFINED ARG_TYPE)
        string(TOLOWER "${ARG_TYPE}" type)
        if(NOT type MATCHES "^(bool|integer|float|string)$")
            message(FATAL_ERROR "snt_dip_get(): TYPE must be BOOL, INTEGER, FLOAT, or STRING.")
        endif()
        list(APPEND type_args --type "${type}")
    endif()
    if(NOT SNT_EXECUTABLE OR NOT EXISTS "${SNT_EXECUTABLE}")
        message(FATAL_ERROR "snt_dip_get(): set SNT_EXECUTABLE to an existing host snt executable. It must be runnable at configure time; cross-compiling requires a host installation.")
    endif()
    get_filename_component(input "${ARG_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${input}")
        message(FATAL_ERROR "snt_dip_get(): DIPL file does not exist: ${input}")
    endif()
    get_filename_component(input_dir "${input}" DIRECTORY)
    set(dependencies "${input}" "${SNT_EXECUTABLE}")
    foreach(dependency IN LISTS ARG_DEPENDS)
        get_filename_component(dependency "${dependency}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        if(NOT EXISTS "${dependency}")
            message(FATAL_ERROR "snt_dip_get(): dependency does not exist: ${dependency}")
        endif()
        list(APPEND dependencies "${dependency}")
    endforeach()
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${dependencies})
    endif()
    execute_process(
        COMMAND "${SNT_EXECUTABLE}" dip parse --input file "${input}" --request "${ARG_PATH}" --value ${type_args}
        WORKING_DIRECTORY "${input_dir}"
        RESULT_VARIABLE result
        OUTPUT_VARIABLE value
        ERROR_VARIABLE error
        TIMEOUT 30
    )
    if(NOT "${result}" STREQUAL "0")
        message(FATAL_ERROR "snt_dip_get(): failed to read '${ARG_PATH}' from '${input}' (exit: ${result}).\n${error}")
    endif()
    # Remove only the CLI record terminator; preserve whitespace in string values.
    string(REGEX REPLACE "\r?\n$" "" value "${value}")
    set(${ARG_OUTPUT} "${value}" PARENT_SCOPE)
endfunction()
