add_library(snt-c STATIC src/puq.cpp src/dip.cpp)
target_include_directories(snt-c PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:include>)
target_link_libraries(snt-c PUBLIC snt-puq snt-dip)
install(TARGETS snt-c EXPORT TargetsSNT ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
