(* ========================================================================= *)
(* PUEL - Physical Unit Expression Language                                  *)
(* ========================================================================= *)

PUEL            = [ System "_" ] Expression ;

(* ========================================================================= *)
(* Expressions                                                               *)
(* ========================================================================= *)

Expression      = Term , { ( "*" | "/" ) , Term } ;

Term            = Value
                | UnitTerm
                | Value , "*" , UnitTerm
                ;

(* ========================================================================= *)
(* Values                                                                    *)
(* ========================================================================= *)

Value           = Number
                | Array
                ;

Array           = "[" , ValueElement , { "," , ValueElement } , "]" ;

ValueElement    = Number ;

(* ========================================================================= *)
(* Numbers                                                                   *)
(* ========================================================================= *)

Number          = [ Sign ] ,
                  Mantissa ,
                  [ Uncertainty ] ,
                  [ ExponentPart ] ;

Mantissa        = Digits , [ "." , Digits ]
                | "." , Digits
                ;

Uncertainty     = "(" , Digits , ")" ;

ExponentPart    = ( "e" | "E" ) , [ Sign ] , Digits ;

Sign            = "+" | "-" ;

(* ========================================================================= *)
(* Units                                                                     *)
(* ========================================================================= *)

UnitTerm        = UnitSymbol , [ UnitExponent ] ;

UnitExponent    = IntegerExponent
                | FractionalExponent
                ;

IntegerExponent = SignedInteger ;

FractionalExponent
                = SignedInteger , ":" , UnsignedInteger ;

(* ========================================================================= *)
(* Identifiers                                                               *)
(* ========================================================================= *)

System          = Identifier ;

UnitSymbol      = Identifier ;

Identifier      = Letter , { Letter | Digit } ;

(* ========================================================================= *)
(* Integers                                                                  *)
(* ========================================================================= *)

SignedInteger   = [ Sign ] , UnsignedInteger ;

UnsignedInteger = Digits ;

Digits          = Digit , { Digit } ;

(* ========================================================================= *)
(* Characters                                                                *)
(* ========================================================================= *)

Letter          = "A".."Z"
                | "a".."z"
                | "µ"
                | "Ω"
                ;

Digit           = "0".."9" ;

(* ========================================================================= *)
(* Examples                                                                  *)
(* ========================================================================= *)

(*
ESU_erg
SI_kg*m2/s2
SI_kg2*m3:2/cm
SI_1.346591(30)e27*kg
SI_[2,3,4,5]*km
*)