expression          = [ unit-system "_" ] , product ;

product             = factor ,
                      { ( "*" | "/" ) , factor } ;

factor              = quantity
                    | unit-system-factor
                    | physical-constant
                    | physical-quantity
                    | grouped-expression
                    | value
                    | unit ;

grouped-expression  = "(" , product , ")" ;

value               = signed-number ,
                      [ uncertainty ] ;

signed-number       = [ sign ] ,
                      number ;

number              = integer
                    | decimal ,
                      [ exponent ] ;

integer             = digit , { digit } ;

decimal             = integer ,
                      [ "." , { digit } ]
                    | "." , digit , { digit } ;

exponent            = ( "e" | "E" ) ,
                      [ sign ] ,
                      integer ;

uncertainty         = "(" , integer , ")" ;

unit                = identifier ,
                      [ exponent-value ] ;

exponent-value      = signed-integer
                    | signed-integer ":" integer ;

signed-integer      = [ sign ] ,
                      integer ;

physical-constant   = "{" , identifier , "}" ;

physical-quantity   = "<" , identifier , ">" ;

unit-system-factor  = "|" , identifier , "|" ;

unit-system         = identifier ;

identifier          = letter ,
                      { letter | digit | "_" } ;

sign                = "+" | "-" ;

letter              = "A"…"Z" | "a"…"z" ;

digit               = "0"…"9" ;
