name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      
    - name: Install and build GTest
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y pybind11-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: build
      run: ./setup.sh -b
      
    - name: test
      run: ./setup.sh -t
