name: Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              ninja-build \
              gcovr

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Configure
        run: |
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_CXX_FLAGS="--coverage" \
            -DCMAKE_C_FLAGS="--coverage" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
            -DCMAKE_SHARED_LINKER_FLAGS="--coverage" \
            -DPython3_EXECUTABLE=$(which python) \
            -DENABLE_UNIT_TESTS=ON \
            -DENABLE_COVERAGE=ON \
            -DENABLE_UNIT_TESTS=ON \
            -DENABLE_COVERAGE=ON

      - name: Build
        run: |
          cmake --build build

      - name: Run tests
        run: |
          ctest \
            --test-dir build \
            --output-on-failure

      - name: Generate coverage report
        run: |
          mkdir -p coverage
          gcovr \
            --root . \
            --search-cwd \
            --gcov-ignore-parse-errors \
            --object-directory build \
            --filter "src" \
            --filter "bindings/python/cpp" \
            --exclude "tests" \
            --exclude "examples" \
            --print-summary \
            --html-details coverage/index.html \
            --xml coverage/coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/            

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/coverage.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

          
