name: Coverage

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'bindings/**'
      - 'benchmarks/**'
      - 'examples/**'
      - 'apps/**'
      - 'tests/**'
      - '.github/workflows/coverage.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'bindings/**'
      - 'benchmarks/**'
      - 'examples/**'
      - 'apps/**'
      - 'tests/**'
      - '.github/workflows/coverage.yml'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              ninja-build \
              gcovr

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest pytest-cmake pytest-benchmark
          #python -m pip install .[test]

      - name: Configure
        run: |
          cmake \
            -B build \
            -G Ninja \
            -DPython3_EXECUTABLE=$(which python) \
            -DENABLE_UNIT_TESTS=ON \
            -DENABLE_COVERAGE=ON

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Run tests
        run: |
          ctest \
            --test-dir build \
            --output-on-failure

      - name: Generate coverage report
        run: |
          mkdir -p coverage
          gcovr \
            --root . \
            --object-directory build \
            --filter "src" \
            --filter "bindings/python/cpp" \
            --exclude "tests" \
            --exclude "examples" \
            --print-summary \
            --html-details coverage/index.html \
            --lcov coverage/coverage.info

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/            

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/coverage.info
          #disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

          
